import { StackNavigationProp } from '@react-navigation/stack';

export type RootStackParamList = {
    Login: undefined;
    Gpay: undefined;
    ScanQRCodeScreen: undefined;
    PayContactScreen: undefined;
    PhnoScreen: undefined;
    MRScreen: undefined;
    JioScreen: undefined;
    AirtelScreen: undefined;
    ViScreen: undefined;
    BSNLScreen: undefined;
    MumbaiScreen: undefined;
    DelhiScreen: undefined;
    MakemytripScreen: undefined;
    BankTransferScreen: undefined;
    PayUpiScreen: undefined;
    PayBillsScreen: undefined;
    SelfTransferScreen: undefined;
    SelectBankScreen: undefined;
    PeopleScreen: undefined;
    RedBusScreen: undefined;
    PrefrScreen: undefined;
    tripScreen: undefined;
    paisaItemScreen: undefined;
    MobileRechargeScreen: undefined;
    ElectricityScreen: undefined;
    TNEBScreen: undefined;
    DthScreen: undefined;
    AirtelTvScreen: undefined;
    SunScreen: undefined;
    DishScreen: undefined;
    TataScreen: undefined;
    D2HScreen: undefined;
    CardScreen: undefined;
    ReferralsScreen: undefined;
    AdaniScreen: undefined;
    AjmerScreen: undefined;
    AndhraScreen: undefined;
    AssamScreen: undefined;
    ArunachalScreen: undefined;
    BesomiScreen: undefined;
    PlayStoreScreen: undefined;
    RewardsScreen: undefined;
    OffersScreen: undefined;
    paisaScreen: undefined;
    storeScreen: undefined;
    FibreLoansScreen: undefined;
};

export type LoginScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Login'>;
